"""initial migration

Revision ID: da79f20b455d
Revises: eb403accd69b
Create Date: 2021-03-15 20:39:41.302094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da79f20b455d'
down_revision = 'eb403accd69b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'status')
    # ### end Alembic commands ###
